---
apiVersion: v1
kind: Namespace
metadata:
  name: mariadb2
---
apiVersion: apps.open-cluster-management.io/v1
kind: Channel
metadata:
  name: mariadb-app2
  namespace: mariadb2
spec:
  type: Git
  pathname: https://github.com/mahesh-zetta/mariadb2.git 
---
apiVersion: apps.open-cluster-management.io/v1
kind: PlacementRule
metadata:
  name: ocp46-acm-openshift2 
  namespace: mariadb2
spec:
  clusterConditions:
    - type: ManagedClusterConditionAvailable
      status: "True"
  clusterSelector:
    matchLabels:
      environment: dev
---
apiVersion: apps.open-cluster-management.io/v1
kind: Subscription
metadata:
  name: mariadb-app2
  namespace: mariadb2
  labels:
    app: mariadb-app2
  annotations:
    apps.open-cluster-management.io/github-path: mariadb-resources
spec:
  channel: mariadb2/mariadb-app2
  placement:
    placementRef:
      kind: PlacementRule
      name: ocp46-acm-openshift2
---
apiVersion: app.k8s.io/v1beta1
kind: Application
metadata:
  name: mariadb-app2
  namespace: mariadb2
spec:
  componentKinds:
  - group: apps.open-cluster-management.io
    kind: Subscription
  descriptor: {}
  selector:
    matchExpressions:
    - key: app
      operator: In
      values:
      - mariadb-app2
