apiVersion: v1
kind: Service
metadata:
  labels:
    app: mariadb2
  name: mariadb2
  namespace: mariadb2
spec:
  ports:
  - name: 3306-tcp
    port: 3306
    protocol: TCP
    targetPort: 3306
  selector:
    app: mariadb2
  sessionAffinity: None
  type: ClusterIP
